version: '3'

includes:
  examples:
    dir: examples
    taskfile: examples/Taskfile.yml

tasks:
  test:
    cmds:
      - gotestsum --format testdox
      - task: examples:test

  lint:
    cmds:
      - golangci-lint run
