version: '3'

tasks:
  test:
    cmds:
      - cmd: |
          cd {{ .ITEM.dir }} &&
          {{ .ITEM.cmd }} | jd {{ .ITEM.expected }}
        for:
          - dir: simple
            cmd: >-
              APP_DATABASE_USERNAME=user
              APP_DATABASE_PASSWORD=pass
              go run main.go
              --debug
              --config=files/override.yaml
            expected: expected.json
